package computerdatabase;
import java.util.*;
import io.gatling.javaapi.core.*;
import io.gatling.javaapi.http.*;
import static io.gatling.javaapi.core.CoreDsl.*;
import static io.gatling.javaapi.http.HttpDsl.*;

public class BasicSimulation extends Simulation{
{
HttpProtocolBuilder httpProtocol = http
.baseUrl("")
.inferHtmlResources(AllowList(), DenyList(".*\\.js", ".*\\.css", ".*\\.gif", ".*\\.jpeg", ".*\\.jpg", ".*\\.ico", ".*\\.woff", ".*\\.woff2", ".*\\.(t|o)tf", ".*\\.png", ".*detectportal\\.firefox\\.com.*"));

Map<CharSequence, String> headers = new HashMap<>();
headers.put("Authorization", "Bearer eyJhbGciOiJSUzI1NiJ9.eyJjbHVzdGVyIjoiQTUyRCIsInByaXZhdGUiOiJleUpqZEhraU9pSktWMVFpTENKbGJtTWlPaUpCTVRJNFEwSkRMVWhUTWpVMklpd2lZV3huSWpvaVpHbHlJbjAuLjF5YjNwdS1BY3FpR2psRUZ1VWtsRUEuWEdQWkk5dUhxeHBiWmJ3UHFnNlJFNnNUNFN6SDdhRG5VVXI3LXVYYkZ6aDRjMDVFYnBkSVJDcGU3cG0yc0FXaE85Y2kzQVJRWEZoSDVaMjFPZXJTSVgtdF91Nmh1YlVHbElxRzBONWVGNlBaY1hzTHF1a001OG90MzJXVVJRaWVQWXlPYzBmMThxbXdnTWJBX0N4Vkphc1p2dHFCNktURzB6cmdpUWV1MUpjWUZzNHA5NnJ2WkpsOHEzVWx6MGtjV0UxTWpobnB4OXkzclk1aHJJMEVmcnRhVmFPc05sNm9pVEFJdk1QcUtMS19lZENWSkIwdnMxdVhmaGwtb2JMMW54RG9jWFEtMjBPX3JMWU1RNVVXRFdyVGh6WS1ISlVSTWxvRFpHLVRjbXpjRVhTNFNLUm5tbThMLVNLNG1qN1FtN1FtZEtCMUN4QVU5WnFWT2I3dlpwMEcxRC0zM01uclVyX2FobnB0N2QzLW5JVXhaeF92OU1wMi1RSnVpSlJGTERqcWFQNnRtLS1Xbnczc2E3RTE5ZGdvSVROSkUxVzQwOTlQTU5YU1dTbTRfYWNvaWozRWFxLXhJb3NabHlqMHgwenNwRDNIYTVtOUxEcU5kVk8yUnVHT0RFR1RYSk9aX1h6ZjhVMEEwQ0tuSWpGYWJINUJJS09NQm1Ob2gtMDFGWUR4X3YzM1B0aExiY2xsSllZYmhVMU9yRW1uWXRodXU0alJsSm8wYTc5bjhNSnJlaU1EdHJ2MEF4Zm05QUxWNFBHUWlFOHlIdWJ3NXllQkQwUXAyMEZ0ZjU1UHFTcnF3c1d6b2hkUVctZTNrWl9BZDNUTzBjN3VFRjNjVVNZWUZ6UVN6cm00bVZkSGZMMTBEUDBMOEpadUlXOUlaVkRYM0RZMEJ6dmwxcFdST1lpME5XRlpBbmx3cUlGXzZkOFBiMUYyZTdkci1XaVdEc2pTM21mbk5tX3piVS0yQ1JxVmwwVEZPOXVqWXMtb0MtUzMtcnYxcGROSHpXcldHVlJyLXltaGdOYTg4T0YyYWJKVjVHdDd4RUl4RXJmcjlMbzlHaUp1cVUtSkduU0ZKRjRRTXFxbFlJeW9ZQjA2aUhWSU5mMng2Vl8yV1MyMDV1QUZ1N0JWUERncmRiZE9aRHM0a1FHTF9TeVU4aktPclRDSC14RXRyV3pnWmV1SDJrZlFDSVNxVWhxOFVJemxyZWhKNmkwNXpOZ0dpb0NDM2UyY2h1cXZiRXl6OFdvLm1LdWg5OU9LNXAyV1hGbjQ2VXctNHciLCJ1c2VyX3R5cGUiOiJ1c2VyIiwidG9rZW5faWQiOiJBYVozcjBNVE14WkRnNE5tVXRaV1pqWVMwMFkySTVMVGszWkdRdE5qTmpPRGxqTlRreE9ERm1NalpsTkRBME16Y3RPVGxqIiwicmVmZXJlbmNlX2lkIjoiNmIxMzA4MDUtZmQ5MS00NzBlLWE5YzgtZTEwNWM0YzM5ZjNjIiwiaXNzIjoiaHR0cHM6XC9cL2lkYnJva2VyYnRzLndlYmV4LmNvbVwvaWRiIiwidXNlcl9tb2RpZnlfdGltZXN0YW1wIjoiMjAyMzExMDgwOTMzMTIuNzYxWiIsInJlYWxtIjoiOGFkNDY4ZDItMjNkYi00OWViLWEyMWEtNzBhMWM5MTc0N2IzIiwiY2lzX3V1aWQiOiI3MDA4NGFhYS0yN2M0LTRkYTQtYTY1ZC1kMjljZDFkMTdmNGQiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiZXhwaXJ5X3RpbWUiOjE3MDAxODI2Nzk2NjYsImNsaWVudF9pZCI6IkNlMDU5OTZhY2Y4ZjA1ZWE5NzQzNDNhYmEwODBkOGUxZDA1NzQwMWM5NTA2Y2E2OTgyNWEwOGVmNjljZmI4NzVhIn0.UQ4pfsx8RtUriG0OESSOi43QpFrgcmBeRuwCg8ukeuBsyK5W_FLA6mRUck0gy9qYVR0fWyEo9QAp0t-jzE_PcCwJHnQ484A1Tbl_fpq8K0iviG0GstfJ4MYbKqmEypWBDYjmK_Mh_-TpGHwv7si-SEFjq1KxKxIQjV2ZJIolpcC2JLFkH7nfsKKX81ZqgqJY_vPdXVBoUb7_WnWVskWwGvzROzhpB8T7Frz2OPxQgjtFQoEcGMIsHiD6iiI5wYozciswjkR2NKLPh-4Hmmz5dB9yO6CXHUpIzxuu0lKFjJrOit9Iki5LGI4HfatYSV1ITqQgOjDiMNCxp_UsoPAI_Q");
headers.put("X-ORGANIZATION-ID", "8ad468d2-23db-49eb-a21a-70a1c91747b3");

  ScenarioBuilder scn = scenario("Desktop APIs load test 25k")
    .exec(http("agent-config api load 25k")
    .get("https://agentx-backend.loadus1.ciscoccservice.com/ab/api/cms/agent-config/70084aaa-27c4-4da4-a65d-d29cd1d17f4d")
    .headers(headers));

setUp(
  scn.injectOpen(
    constantUsersPerSec(25).during(1000)
  ).protocols(httpProtocol)
);
}
}

